# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\python\rest\setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 145)
        MainWindow.setMinimumSize(QtCore.QSize(400, 145))
        MainWindow.setMaximumSize(QtCore.QSize(400, 145))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.jiangeLabel = QtWidgets.QLabel(self.centralwidget)
        self.jiangeLabel.setObjectName("jiangeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.jiangeLabel)
        self.between = QtWidgets.QSpinBox(self.centralwidget)
        self.between.setObjectName("between")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.between)
        self.lastLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastLabel.setObjectName("lastLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lastLabel)
        self.last = QtWidgets.QSpinBox(self.centralwidget)
        self.last.setObjectName("last")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.last)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "设置"))
        self.jiangeLabel.setText(_translate("MainWindow", "休息时间间隔(单位:分钟)"))
        self.lastLabel.setText(_translate("MainWindow", "休息时间(单位:分钟)"))
        self.pushButton.setText(_translate("MainWindow", "保存设置(重启后生效)"))
